from dataclasses import dataclass, field

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from .config import IMPORT_TO_PIP, STDLIB_MODULES


@dataclass
class CellEntry:
    """A single file's contribution to the notebook."""

    filename: str
    code: str
    docstring: str | None = None


@dataclass
class Section:
    """A group of related files (one independent sub-project)."""

    name: str | None
    cells: list[CellEntry] = field(default_factory=list)
    external_imports: list[str] = field(default_factory=list)
    registered_modules: list[str] = field(default_factory=list)


def build_notebook(
    readme_content: str | None,
    data_files: list[str],
    external_imports: list[str],
    cells: list[tuple[str, str, str | None]],
    include_pip_install: bool = False,
    sections: list[Section] | None = None,
) -> nbformat.NotebookNode:
    """Assemble a complete Jupyter notebook from the processed cells.

    When *sections* is provided, the notebook is built from sections
    (ignoring *cells* and *external_imports*).  Otherwise the flat
    *cells* list is used for backwards compatibility.
    """
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    header = "*Auto-generated by [rep2nb](https://pypi.org/project/rep2nb/) — a tool that converts Python repos into executable notebooks.*"
    if readme_content:
        nb.cells.append(new_markdown_cell(f"{header}\n\n---\n\n{readme_content}"))
    else:
        nb.cells.append(new_markdown_cell(header))

    if data_files:
        notice = (
            "### Required Data Files\n\n"
            "The following non-Python files from the repository should be "
            "present in the working directory for the notebook to run "
            "correctly:\n\n"
        )
        for f in data_files:
            notice += f"- `{f}`\n"
        nb.cells.append(new_markdown_cell(notice))

    if sections is not None:
        all_ext: list[str] = []
        for sec in sections:
            all_ext.extend(sec.external_imports)
        if include_pip_install:
            pip_packages = _resolve_pip_names(all_ext)
            if pip_packages:
                nb.cells.append(new_code_cell(
                    _pip_install_source(pip_packages)
                ))
        _append_sections(nb, sections)
    else:
        if include_pip_install:
            pip_packages = _resolve_pip_names(external_imports)
            if pip_packages:
                nb.cells.append(new_code_cell(
                    _pip_install_source(pip_packages)
                ))
        _append_flat_cells(nb, cells)

    return nb


def _append_flat_cells(
    nb: nbformat.NotebookNode,
    cells: list[tuple[str, str, str | None]],
) -> None:
    for filename, code, docstring in cells:
        if docstring:
            nb.cells.append(new_markdown_cell(
                f"#### `{filename}`\n\n{docstring}"
            ))
        basename = filename.rsplit("/", 1)[-1]
        file_line = f"__file__ = {basename!r}\n"
        cell_source = f"# === {filename} ===\n\n{file_line}{code.rstrip()}\n"
        nb.cells.append(new_code_cell(cell_source))


def _append_sections(
    nb: nbformat.NotebookNode,
    sections: list[Section],
) -> None:
    show_headers = len(sections) > 1 or (
        len(sections) == 1 and sections[0].name is not None
    )

    for idx, sec in enumerate(sections):
        if show_headers and sec.name:
            nb.cells.append(new_markdown_cell(f"## {sec.name}"))

        if sec.name and show_headers:
            chdir_cell = (
                f"import os as _os; _os.makedirs({sec.name!r}, exist_ok=True); "
                f"_os.chdir({sec.name!r}); del _os"
            )
            nb.cells.append(new_code_cell(chdir_cell))

        for entry in sec.cells:
            if entry.docstring:
                nb.cells.append(new_markdown_cell(
                    f"#### `{entry.filename}`\n\n{entry.docstring}"
                ))
            basename = entry.filename.rsplit("/", 1)[-1]
            file_line = f"__file__ = {basename!r}\n"
            cell_source = f"# === {entry.filename} ===\n\n{file_line}{entry.code.rstrip()}\n"
            nb.cells.append(new_code_cell(cell_source))

        cleanup_parts: list[str] = []

        if sec.name and show_headers:
            cleanup_parts.append(
                "import os as _os; _os.chdir('..')\n"
                "try:\n"
                f"    _os.rmdir({sec.name!r})\n"
                "except OSError:\n"
                "    pass\n"
                "del _os"
            )

        if idx < len(sections) - 1 and sec.registered_modules:
            mods_literal = ", ".join(repr(m) for m in sec.registered_modules)
            cleanup_parts.append(
                "import sys as _sys\n"
                f"for _k in [{mods_literal}]:\n"
                "    _sys.modules.pop(_k, None)\n"
                "del _sys, _k"
            )

        if cleanup_parts:
            nb.cells.append(new_code_cell(
                "# --- rep2nb: section cleanup ---\n"
                + "\n".join(cleanup_parts)
            ))


def _resolve_pip_names(external_imports: list[str]) -> list[str]:
    """Map import root names to pip package names, excluding stdlib."""
    packages: list[str] = []
    seen: set[str] = set()
    for imp in external_imports:
        root = imp.split(".")[0]
        if root in STDLIB_MODULES or root in seen:
            continue
        seen.add(root)
        packages.append(IMPORT_TO_PIP.get(root, root))
    return packages


def _pip_install_source(packages: list[str]) -> str:
    pkg_str = " ".join(sorted(packages))
    return (
        "import sys as _sys\n"
        f"!{{_sys.executable}} -m pip install -q {pkg_str}\n"
        "del _sys"
    )
